binary_sensor:

  - id: zone9
    name: Zone 9    
    pin:
      number: $zone9
      mode: INPUT #INPUT_PULLUP
    platform: gpio   
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      - if:
          condition:
            lambda: 'return x;'
          then:
            - light.addressable_set:
                id: zonelights
                range_from: 8
                range_to: 8
                red: 50%
                green: 0%
                blue: 0%
          else:
            - light.addressable_set:
                id: zonelights
                range_from: 8
                range_to: 8
                red: 0%
                green: 50%
                blue: 0%
      - if:
          condition:
            lambda: return id(blink_on_state);
          then:
            - script.execute: blink_status_led